################################################################################
# General settings
title: Sandbox
author: Caspar

################################################################################
# Notebook execution on compiling
execute:
  execute_notebooks: false
  timeout: 60 
  allow_errors: false

################################################################################
# Sphinx settings
sphinx:
  extra_extensions:
  - jupyterlite_sphinx
  config:
    jupyterlite_config: jupyterlite-config.json
    # Bibliography style
    bibtex_reference_style: author_year
    # Use newer version of Mathjax for latex equation formatting
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


